### PR TITLE
feat: download ngrock binary on activation

### LINKED ISSUE #7: Download system specific binary on extension activation.
The current version has the Mac binary packaged that was installed when I installed the npm ngrok package. This doesn't work on other OSes.

The extension should kick off a download for the correct binary on the first activation. The ngrok package does have a [postinstall download script](https://github.com/bubenshchykov/ngrok/blob/master/download.js) which this could use or be based on.

Some work for this has been attempted in #5, but I wanted to raise a separate issue to capture this.

### PR DESCRIPTION
**Pull request by Michsior14**
Resolves #7.

### CODE REVIEW

**Comment by Michsior14** [comment]
The only thing I am not sure of is if the downloaded binary will be chosen instead of the one provided in `node_modules`.

**Comment by philnash** [comment]
The ngrok module picking the locally installed binary is handled in these lines: https://github.com/bubenshchykov/ngrok/blob/master/process.js#L4-L5, so it should act as expected.

**Comment by philnash** [comment]
This has been released as version 1.2.0.

I added one check to make sure the extension doesn't download ngrok (or unzip it from it's cached version) every time.

If you're on a machine that isn't a Mac I'd love if you could try and confirm that 1.2.0 is now working. 

Thanks for your help with this.

**Comment by Michsior14** [comment]
> This has been released as version 1.2.0.
> 
> I added one check to make sure the extension doesn't download ngrok (or unzip it from it's cached version) every time.
> 
> If you're on a machine that isn't a Mac I'd love if you could try and confirm that 1.2.0 is now working.
> 
> Thanks for your help with this.

Yep, works for me on Linux ;) BTW. We could also provide "update" command by just executing `ngrok update` on downloaded binary.

**Comment by philnash** [comment]
Yeah, I’ve got ideas for further things to add here. And that’s a good one.

Just needed to get this out so that it worked for everyone!

**Pull request merged**
